### ISSUE TITLE
ImportError: No module named 'django_extensions'

### ISSUE THREAD

**Issue by cameron-jack** [beukueb/myflq#4]
I'm keen to use your pipeline, but when I use the documented docker instructions:
sudo docker pull beukueb/myflq #Only necessary to ensure using latest version
sudo docker run -p 0.0.0.0:80:8000 -i -t --entrypoint webapp beukueb/myflq

I get the following:
cam@lightning:~$ sudo docker run -p 0.0.0.0:80:8000 -i -t --entrypoint webapp beukueb/myflq
spawn python3 manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'django_extensions'
expect: spawn id exp6 not open
    while executing
"expect "Username" { send "admin\r" }"
For administrative use, go to http://localhost/admin
You can log in with user 'admin' and password 'myfl1234admin'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'django_extensions'
root@1078afd7685d:/myflq/MyFLsite#

**Comment by beukueb** [comment]
The dockerfile was no longer uptodate and did not contain all the dependencies anymore. I will fix that. 

If you want to use MyFLq in the meantime, you can also install it inside of a python virtualenv.

**Comment by beukueb** [comment]
Working again

**Comment by cameron-jack** [comment]
Thanks!
